=== Hardziyevich/task2/src/main/resources/CandyScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/entity"
        xmlns:tns="http://www.example.org/entity">


    <simpleType name="CandyType">
        <restriction base="string">
            <enumeration value="caramel"/>
            <enumeration value="chocolate"/>
            <enumeration value="chocolate-filling"/>
        </restriction>
    </simpleType>

    <simpleType name="ChocolateType">
        <restriction base="string">
            <enumeration value="white"/>
            <enumeration value="not-white"/>
        </restriction>
    </simpleType>

    <complexType name="IngredientImpl">
        <attribute name="water" use="required" type="tns:milligrams"/>
        <attribute name="sugar" use="required" type="tns:milligrams"/>
        <attribute name="fructose" use="required" type="tns:milligrams"/>
        <attribute name="vanilla" use="required" type="tns:milligrams"/>
<!--        <attribute name="chocolate-type" use="optional" type="tns:ChocolateType" default="unknown"/>-->
    </complexType>

    <complexType name="NutritionalValueImpl">
        <sequence>
            <element name="fat" type="int" />
            <element name="protein" type="int"/>
            <element name="carb" type="int"/>
        </sequence>
    </complexType>

    <simpleType name="CandyId">
        <restriction base="long">
            <pattern value="\d{2}"/>
            <minExclusive value="0"/>
        </restriction>
    </simpleType>

    <simpleType name="milligrams">
        <restriction base="double">
            <pattern value="\d[.](\d{3})"/>
            <maxExclusive value="0.999"/>
        </restriction>
    </simpleType>

    <complexType name="Candy">
        <sequence>
            <element name="energy" type="int"/>
            <element name="name-candy" type="string"/>
            <element name="production" type="string"/>
            <element name="ingredient" type="tns:IngredientImpl"/>
            <element name="value" type="tns:NutritionalValueImpl"/>
            <element name="shelf-life" type="dateTime"/>
        </sequence>
        <attribute name="id" use="required" type="tns:CandyId"/>
    </complexType>

    <complexType name="CaramelCandy">
        <complexContent>
            <extension base="tns:Candy">
                <attribute name="candy-type" type="tns:CandyType" use="required" fixed="caramel"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="ChocolateCandy">
        <complexContent>
            <extension base="tns:Candy">
                <attribute name="candy-type" type="tns:CandyType" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <element name="Candies" type="tns:Candy" abstract="true"></element>

    <element name="Caramel" type="tns:CaramelCandy" substitutionGroup="tns:Candies"></element>

    <element name="Chocolate" type="tns:ChocolateCandy" substitutionGroup="tns:Candies"></element>

    <element name="Entity">
        <complexType>
            <sequence>
                <element ref="tns:Candies" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>

</schema>

=== Hardziyevich/task2/src/main/resources/Candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<Entity xmlns:tns="http://www.example.org/entity"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/entity CandyScheme.xsd">


    <Chocolate id="12" chocolate="chocolate-filling" chocolate-filling="not-white">
        <energy>10</energy>
        <name-candy>Alenka</name-candy>
        <production>Komunarka</production>
        <ingredient water="0.001" sugar="0.001" fructose="0.001" vanilla="0.001"/>
        <value>
            <fat>1</fat>
            <protein>1</protein>
            <carb>1</carb>
        </value>
        <shelf-life>2002-05-30T09:00:00</shelf-life>
    </Chocolate>

    <Caramel id="13" candy-type="glaze">
        <energy>14</energy>
        <name-candy>Mashka</name-candy>
        <production>Komunarka</production>
        <ingredient water="0.002" sugar="0.002" fructose="0.002" vanilla="0.002"/>
        <value>
            <fat>14</fat>
            <protein>11</protein>
            <carb>123</carb>
        </value>
        <shelf-life>2002-05-30T09:00:00</shelf-life>
    </Caramel>

    <Chocolate id="14" chocolate="chocolate">
        <energy>153</energy>
        <name-candy>Pushka</name-candy>
        <production>Komunarka</production>
        <ingredient water="0.003" sugar="0.003" fructose="0.003" vanilla="0.003"/>
        <value>
            <fat>11</fat>
            <protein>12</protein>
            <carb>13</carb>
        </value>
        <shelf-life>2002-05-30T09:00:00</shelf-life>
    </Chocolate>


</Entity>

=== Hardziyevich/task2/src/main/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Entity xmlns:tns="http://www.example.org/entity"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/entity CandyScheme.xsd">

    <tns:Chocolate id="12" candy-type="chocolate">
        <energy>10</energy>
        <name-candy>Alenka</name-candy>
        <production>Komunarka</production>
        <ingredient water="0.001" sugar="0.001" fructose="0.001" vanilla="0.001"/>
        <value>
            <fat>1</fat>
            <protein>1</protein>
            <carb>1</carb>
        </value>
        <shelf-life>2002-05-30T09:00:00</shelf-life>
    </tns:Chocolate>

    <tns:Caramel id="13" candy-type="caramel">
        <energy>14</energy>
        <name-candy>Mashka</name-candy>
        <production>Komunarka</production>
        <ingredient water="0.002" sugar="0.002" fructose="0.002" vanilla="0.002"/>
        <value>
            <fat>14</fat>
            <protein>11</protein>
            <carb>123</carb>
        </value>
        <shelf-life>2002-05-30T09:00:00</shelf-life>
    </tns:Caramel>

    <tns:Chocolate id="14" candy-type="">
        <energy>153</energy>
        <name-candy>Pushka</name-candy>
        <production>Komunarka</production>
        <ingredient water="0.003" sugar="0.003" fructose="0.003" vanilla="0.003"/>
        <value>
            <fat>11</fat>
            <protein>12</protein>
            <carb>13</carb>
        </value>
        <shelf-life>2002-05-30T09:00:00</shelf-life>
    </tns:Chocolate>


</tns:Entity>
